#!/usr/bin/env python3
"""
Check PMC status for test PMIDs.
Outputs which papers are in PMC vs not.
"""

import os
import sys
import time

# Add parent to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from Bio import Entrez
from pathlib import Path

# Configure Entrez
Entrez.email = os.getenv("NCBI_EMAIL", "brett.kroncke@vumc.org")
Entrez.api_key = os.getenv("NCBI_API_KEY")

RATE_LIMIT = 0.11 if Entrez.api_key else 0.34


def pmid_to_pmcid(pmid: str) -> str | None:
    """Convert PMID to PMCID. Returns None if not in PMC."""
    try:
        time.sleep(RATE_LIMIT)
        handle = Entrez.elink(dbfrom="pubmed", db="pmc", id=pmid, linkname="pubmed_pmc")
        record = Entrez.read(handle)
        handle.close()

        if record[0]["LinkSetDb"]:
            pmc_ids = record[0]["LinkSetDb"][0]["Link"]
            if pmc_ids:
                return f"PMC{pmc_ids[0]['Id']}"
        return None
    except Exception as e:
        print(f"  Error for {pmid}: {e}", file=sys.stderr)
        return None


def main():
    # Read test PMIDs
    test_file = Path(__file__).parent.parent / "tests/fixtures/pmids/test_pmids.txt"

    pmids = []
    current_category = None
    categories = {}

    with open(test_file) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                # Track category headers
                if "CATEGORY" in line:
                    current_category = line
                continue

            pmid = line.split()[0]  # Get just the PMID before any comment
            pmids.append(pmid)
            categories[pmid] = current_category

    print(f"Checking {len(pmids)} PMIDs for PMC status...\n")

    in_pmc = []
    not_in_pmc = []

    for i, pmid in enumerate(pmids, 1):
        pmcid = pmid_to_pmcid(pmid)
        status = "✓ PMC" if pmcid else "✗ NO PMC"
        cat_short = (
            categories.get(pmid, "").split(":")[0].replace("# ", "")
            if categories.get(pmid)
            else ""
        )
        print(f"[{i}/{len(pmids)}] {pmid}: {status} {f'({pmcid})' if pmcid else ''}")

        if pmcid:
            in_pmc.append((pmid, pmcid, cat_short))
        else:
            not_in_pmc.append((pmid, cat_short))

    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"\nIn PMC: {len(in_pmc)}")
    print(f"NOT in PMC: {len(not_in_pmc)}")

    if not_in_pmc:
        print(f"\n--- Papers NOT in PMC ({len(not_in_pmc)}) ---")
        for pmid, cat in not_in_pmc:
            print(f"  {pmid}  # {cat}")

    # Write non-PMC PMIDs to a file for testing
    output_file = (
        Path(__file__).parent.parent / "tests/fixtures/pmids/non_pmc_pmids.txt"
    )
    with open(output_file, "w") as f:
        f.write("# Test PMIDs that are NOT in PubMed Central\n")
        f.write("# These require alternative download strategies\n")
        f.write(f"# Generated by check_pmc_status.py\n\n")
        for pmid, cat in not_in_pmc:
            f.write(f"{pmid}  # {cat}\n")

    print(f"\nWrote non-PMC PMIDs to: {output_file}")


if __name__ == "__main__":
    main()
